config/routes.rb
Rails.application.routes.draw do
  # toppages
  root to: 'toppages#index'

  # sessions
  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # users
  get   'signup', to: 'users#new'
  post  'signup', to: 'users#create'
  patch '/users/:id/edit', to: 'users#update'
  resources :users, only: [:show, :edit, :update] do
    member do
      get :following, :followers
    end
  end

  # ranking
  get 'rankings/favo', to: 'rankings#favo'
  get 'rankings/play', to: 'rankings#play'

  # items
  resources :items,         only: [:show, :new]
  # ownerships
  resources :ownerships,    only: [:create, :destroy]
  # relationships
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # ownerships
  has_many :ownerships
  has_many :items, through: :ownerships
  # ItemFavo
  has_many :favos
  has_many :favo_items, through: :favos, class_name: 'Item', source: :item
  # ItemPlay
  has_many :plays, class_name: 'Play'
  has_many :play_items, through: :plays, class_name: 'Item', source: :item

  # relationships
  has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  # 渡された文字列のハッシュ値を返す
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # rememberトークンをnilにする
  def forget
    update_attribute(:remember_digest, nil)
  end

                # follow関係のメソッド
  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

                # Favo関係のメソッド
  # itemをfavo
  def favo(item)
    self.favos.find_or_create_by(item_id: item.id)
  end

  # Favoの取消
  def unfavo(item)
    favo = self.favos.find_by(item_id: item.id)
    favo.destroy if favo
  end

  # Favoしているか確認
  def favo?(item)
    self.favo_items.include?(item)
  end

                # Play関係のメソッド
  # itemをplay
  def play(item)
    self.plays.find_or_create_by(item_id: item.id)
  end

  # Playの取消
  def unplay(item)
    play = self.plays.find_by(item_id: item.id)
    play.destroy if play
  end

  # Playしているか確認
  def play?(item)
    self.play_items.include?(item)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :user_find,      only: [:show, :edit, :update,
                                        :following, :followers]
  before_action :counts,    only: [:show, :following, :followers]

  def show
    @items = @user.items.uniq
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'ユーザーを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザーの登録に失敗しました。'
      render :new
    end
  end

  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "プロフィールを編集しました。"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def following
    @title = "Following"
    @users = @user.following.page(params[:page])
    render 'show_follow'
  end
  
  def followers
    @title = "Followers"
    @users = @user.followers.page(params[:page])
    render 'show_follow'
  end

  private

    def user_params
      params.require(:user).permit(:name, :email,
                                   :password, :password_confirmation)
    end

    def user_find
      @user  = User.find(params[:id])
    end

    def counts
      @count_favo = @user.favo_items.count
      @count_play = @user.play_items.count
      @count_following = @user.following.count
      @count_followers = @user.followers.count
    end

end

app/helpers/users_helper.rb
module UsersHelper
    # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, size: 100)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "img-circle")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary btn-sm" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:url)) do |f|%>
  <%= render 'layouts/error_messages', object: f.object %>

  <div class="form-group">
    <%= f.label :name, 'ユーザーネーム' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email, 'メールアドレス' %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, 'パスワード（確認）' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <div class="text-right">
    <%= f.submit yield(:button_text), class: 'btn btn-success' %>
  </div>
<% end %>

app/views/users/_navtabs.html.erb
<ul class="nav nav-tabs nav-justified">
  <li class="<%= 'active' if current_page?(user_path(user))%>">
    <%= link_to user_path(user) do %>
      Games
    <% end %>
  </li>
  <li class="<%= 'active' if current_page?(following_user_path(user)) %>">
    <%= link_to following_user_path(user) do %>
      Following
    <% end %>
  </li>
  <li class="<%= 'active' if current_page?(followers_user_path(user)) %>">
    <%= link_to followers_user_path(user) do %>
      Followers
    <% end %>
  </li>
</ul>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-default btn-sm" %>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="media-list">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-left">
          <%= gravatar_for user, size: 50 %>
        </div>
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "プロフィール編集") %>
<% provide(:url, edit_user_path(@user)) %>
<% provide(:button_text, '保存する') %>
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="panel panel-default">
      <div class="panel-heading">プロフィール編集</div>
      <div class="gravatar-edit">
        <div class="icon text-center">
          <%= gravatar_for(@user, size: 80) %>
        </div>
        <div class="text-center" id="change-button">
          <a href="http://gravatar.com/emails" target="_blank" rel="noopener"
             class="btn btn-default btn-xs">
            <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>
            change
          </a>
        </div>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "ユーザー登録") %>
<% provide(:url, signup_path) %>
<% provide(:button_text, "登録する") %>
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="panel panel-default">
      <div class="panel-heading">ユーザー登録</div>
      <div class="panel-body">
        <%= render 'form'%>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "#{@user.name}のマイページ") %>
<div class="user-profile">
  <div class="icon text-center">
    <%= gravatar_for @user %>
  </div>
  <div class="name text-center">
    <h1><%= @user.name %></h1>
  </div>
  <div class="status text-center">
    <ul>
      <li>
        <div class="status-label">Favo</div>
        <div id="favo_count" class="status-value">
          <%= @count_favo %>
        </div>
      </li>
      <li>
        <div class="status-label">Play</div>
        <div id="play_count" class="status-value">
          <%= @count_play %>
        </div>
      </li>
    </ul>
  </div>
</div>
<%= render 'navtabs', user: @user %>
<%= render 'items/items', items: @items %>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="user-profile">
  <div class="icon text-center">
    <%= gravatar_for @user %>
  </div>
  <div class="name text-center">
    <h1><%= @user.name %></h1>
    <%= render 'follow_form' if logged_in? %>
  </div>
  <div class="status text-center">
    <ul>
      <li>
        <div class="status-label">Favo</div>
        <div id="favo_count" class="status-value">
          <%= @count_favo %>
        </div>
      </li>
      <li>
        <div class="status-label">Play</div>
        <div id="play_count" class="status-value">
          <%= @count_play %>
        </div>
      </li>
      <%= render 'shared/stats' %>
    </ul>
  </div>
</div>
<%= render 'navtabs', user: @user %>
<div class="nav-contents">
  <div class="col-xs-offset-4 col-xs-8">
    <%= render 'users', users: @users %>
  </div>
</div>