config/routes.rb
Rails.application.routes.draw do
  # toppages
  root to: 'toppages#index'

  # sessions
  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # users
  get   'signup', to: 'users#new'
  post  'signup', to: 'users#create'
  patch '/users/:id/edit', to: 'users#update'
  resources :users, only: [:show, :edit, :update] do
    member do
      get :following, :followers
    end
  end

  # ranking
  get 'rankings/favo', to: 'rankings#favo'
  get 'rankings/play', to: 'rankings#play'

  # items
  resources :items,         only: [:show, :new]
  # ownerships
  resources :ownerships,    only: [:create, :destroy]
  # relationships
  resources :relationships, only: [:create, :destroy]
end

app/models/ownership.rb
class Ownership < ApplicationRecord
  validates :user_id, presence: true
  validates :item_id, presence: true

  belongs_to :user
  belongs_to :item
end

app/controllers/ownerships_controller.rb
class OwnershipsController < ApplicationController

  def create
    @item = Item.find_or_initialize_by(code: params[:item_code])

    # @itemが保存されていない場合、先に @item を保存する
    unless @item.persisted?
      results = RakutenWebService::Books::Game.search({jan: @item.code,
                                                       outOfStockFlag: 1})
      @item = Item.new(read(results.first))
      @item.save
    end

    # Favo関係として保存
    if params[:type] == 'Favo'
      current_user.favo(@item)
      flash[:success] = "ゲームを Favo に登録しました。"
    # Play関係として保存
    elsif params[:type] == 'Play'
      current_user.play(@item)
      flash[:success] = "ゲームを Play に登録しました。"
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @item = Item.find(params[:item_id])

    if params[:type] == 'Favo'
      current_user.unfavo(@item)
      flash[:danger] = 'ゲームを Favo から外しました。'
    elsif params[:type] == 'Play'
      current_user.unplay(@item)
      flash[:danger] = 'ゲームを Play から外しました。'
    end
    redirect_back(fallback_location: root_path)
  end
end

app/views/ownerships/_favo_button.html.erb
<% if current_user.favo?(item)%>
  <%= form_tag(ownership_path(item.id), method: :delete) do %>
    <%= hidden_field_tag :item_id, item.id %>
    <%= hidden_field_tag :type, 'Favo' %>
    <%= submit_tag 'Favo', class: 'btn btn-default' %>
  <% end %>
<% else %>
  <%= form_tag(ownerships_path) do %>
    <%= hidden_field_tag :item_code, item.code %>
    <%= hidden_field_tag :type, 'Favo' %>
    <%= submit_tag 'Favo it', class: 'btn btn-danger' %>
  <% end %>
<% end%>

app/views/ownerships/_play_button.html.erb
<% if current_user.play?(item) %>
  <%= form_tag(ownership_path(item.id), method: :delete) do %>
    <%= hidden_field_tag :item_id, item.id %>
    <%= hidden_field_tag :type, 'Play' %>
    <%= submit_tag 'Play', class: 'btn btn-default' %>
  <% end %>
<% else %>
  <%= form_tag(ownerships_path) do %>
    <%= hidden_field_tag :item_code, item.code %>
    <%= hidden_field_tag :type, 'Play' %>
    <%= submit_tag 'Play it', class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/ownerships/_want_button.html.erb
<% if current_user.favo?(item)%>
  <%= form_tag(ownership_path(item.id), method: :delete) do %>
    <%= hidden_field_tag :item_id, item.id %>
    <%= hidden_field_tag :type, 'Favo' %>
    <%= submit_tag 'Favo', class: 'btn btn-default' %>
  <% end %>
<% else %>
  <%= form_tag(ownerships_path) do %>
    <%= hidden_field_tag :item_code, item.code %>
    <%= hidden_field_tag :type, 'Favo' %>
    <%= submit_tag 'Favo it', class: 'btn btn-danger' %>
  <% end %>
<% end%>