config/routes.rb
Rails.application.routes.draw do
  # toppages
  root to: 'toppages#index'

  # sessions
  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # users
  get   'signup', to: 'users#new'
  post  'signup', to: 'users#create'
  patch '/users/:id/edit', to: 'users#update'
  resources :users, only: [:show, :edit, :update] do
    member do
      get :following, :followers
    end
  end

  # ranking
  get 'rankings/favo', to: 'rankings#favo'
  get 'rankings/play', to: 'rankings#play'

  # items
  resources :items,         only: [:show, :new]
  # ownerships
  resources :ownerships,    only: [:create, :destroy]
  # relationships
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<div class="col-xs-offset-3 col-xs-6">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center text-muted">© 2018 GAMEBOYS.</div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-left" href="/"><img src="/images/logo.png" alt="Gameboys"></a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
              <%= link_to new_item_path do %>
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                ゲームを検索
              <% end %>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                 role="button" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-signal" aria-hidden="true"></span>
                ランキング
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Favoランキング', rankings_favo_path %></li>
                <li><%= link_to 'Playランキング', rankings_play_path %></li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                 role="button" aria-haspopup="true" aria-expanded="false">
                <span class="gravatar"><%= gravatar_for(current_user, size: 20)%></span>
                <%= current_user.name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'マイページ', user_path(current_user) %>
                </li>
                <li>
                  <%= link_to "プロフィール編集", edit_user_path(current_user) %>
                </li>
                <li role="separator" class="divider"></li>
                <li>
                  <%= link_to 'ログアウト', logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to '新規登録', signup_path %></li>
            <li><%= link_to 'ログイン', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- app/assets/stylesheets -->
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- app/assets/javascripts-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap JavaScript-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <%= yield :cover %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>
    </div>
    <div class="container">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>